# -*- coding: utf-8 -*-

"""
    falconideapiv10.models.attributes

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class Attributes(object):

    """Implementation of the 'attributes' model.

    TODO: type model description here.

    Attributes:
        name (list of string): TODO: type description here.
        regid (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name" : "NAME",
        "regid" : "REGID"
    }

    def __init__(self,
                 name=None,
                 regid=None):
        """Constructor for the Attributes class"""

        # Initialize members of the class
        self.name = name
        self.regid = regid


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get("NAME")
        regid = dictionary.get("REGID")

        # Return an object of this model
        return cls(name,
                   regid)


